const word = [
  {
    id: 1,
    level: 1,
    word: "the",
    meaning: "সর্বনাম (অণু নিবন্ধক)",
    pronunciation: "দ্য",
  },
  { id: 2, level: 1, word: "be", meaning: "হওয়া", pronunciation: "বি" },
  {
    id: 3,
    level: 1,
    word: "to",
    meaning: "প্রতি / উদ্দেশ্যে",
    pronunciation: "টু",
  },
  { id: 4, level: 1, word: "of", meaning: "এর", pronunciation: "অভ" },
  { id: 5, level: 1, word: "and", meaning: "এবং", pronunciation: "অ্যান্ড" },
  { id: 6, level: 1, word: "a", meaning: "একটি", pronunciation: "এ" },
  {
    id: 7,
    level: 1,
    word: "in",
    meaning: "অভ্যন্তরে / মধ্যে",
    pronunciation: "ইন",
  },
  { id: 8, level: 1, word: "that", meaning: "যে", pronunciation: "দ্যাট" },
  { id: 9, level: 1, word: "have", meaning: "থাকা", pronunciation: "হ্যাভ" },
  { id: 10, level: 1, word: "I", meaning: "আমি", pronunciation: "আই" },
  { id: 11, level: 1, word: "it", meaning: "এই / এটি", pronunciation: "ইট" },
  { id: 12, level: 1, word: "for", meaning: "জন্য", pronunciation: "ফোর" },
  { id: 13, level: 1, word: "not", meaning: "না", pronunciation: "নট" },
  { id: 14, level: 1, word: "on", meaning: "উপর", pronunciation: "অন" },
  { id: 15, level: 1, word: "with", meaning: "সাথে", pronunciation: "উইথ" },
  { id: 16, level: 1, word: "he", meaning: "সে (পু.)", pronunciation: "হি" },
  {
    id: 17,
    level: 1,
    word: "as",
    meaning: "মতো / ব্যবহৃত",
    pronunciation: "অ্‌যাজ",
  },
  {
    id: 18,
    level: 1,
    word: "you",
    meaning: "তুমি / আপনি",
    pronunciation: "ইউ",
  },
  { id: 19, level: 1, word: "do", meaning: "করা", pronunciation: "ডু" },
  { id: 20, level: 1, word: "at", meaning: "এতে / এ", pronunciation: "অ্যাট" },
  { id: 21, level: 1, word: "this", meaning: "এই", pronunciation: "দিস্" },
  { id: 22, level: 1, word: "but", meaning: "কিন্তু", pronunciation: "বাট" },
  { id: 23, level: 1, word: "his", meaning: "তার (পু.)", pronunciation: "হিজ" },
  { id: 24, level: 1, word: "by", meaning: "দ্বারা", pronunciation: "বাই" },
  { id: 25, level: 1, word: "from", meaning: "থেকে", pronunciation: "ফ্রম" },
  { id: 26, level: 1, word: "they", meaning: "তারা", pronunciation: "দেই" },
  { id: 27, level: 1, word: "we", meaning: "আমরা", pronunciation: "উই" },
  {
    id: 28,
    level: 1,
    word: "say",
    meaning: "বোঝানো / বলা",
    pronunciation: "সে",
  },
  { id: 29, level: 1, word: "her", meaning: "তার (মু.)", pronunciation: "হার" },
  { id: 30, level: 1, word: "she", meaning: "সে (মু.)", pronunciation: "শি" },
  { id: 31, level: 1, word: "or", meaning: "অথবা", pronunciation: "অর" },
  {
    id: 32,
    level: 1,
    word: "an",
    meaning: "একটি (স্বরবর্ণ আগে)",
    pronunciation: "এন",
  },
  {
    id: 33,
    level: 1,
    word: "will",
    meaning: "ইচ্ছা / ভবিষ্যৎ চিহ্ন",
    pronunciation: "উইল",
  },
  { id: 34, level: 1, word: "my", meaning: "আমার", pronunciation: "মাই" },
  { id: 35, level: 1, word: "one", meaning: "এক", pronunciation: "ওয়ান" },
  { id: 36, level: 1, word: "all", meaning: "সব", pronunciation: "অল" },
  { id: 37, level: 1, word: "would", meaning: "হতো", pronunciation: "উড" },
  { id: 38, level: 1, word: "there", meaning: "ওখানে", pronunciation: "দ্যার" },
  {
    id: 39,
    level: 1,
    word: "their",
    meaning: "তাদের",
    pronunciation: "দেয়ার",
  },
  { id: 40, level: 1, word: "what", meaning: "কি", pronunciation: "হোয়াট" },
  { id: 41, level: 1, word: "so", meaning: "তাই / অতঃপর", pronunciation: "সো" },
  { id: 42, level: 1, word: "up", meaning: "উপর", pronunciation: "আপ" },
  { id: 43, level: 1, word: "out", meaning: "বাইরে", pronunciation: "আউট" },
  { id: 44, level: 1, word: "if", meaning: "যদি", pronunciation: "ইফ" },
  {
    id: 45,
    level: 1,
    word: "about",
    meaning: "সম্পর্কে",
    pronunciation: "অ্যাবাউট",
  },
  { id: 46, level: 1, word: "who", meaning: "কে", pronunciation: "হু" },
  { id: 47, level: 1, word: "get", meaning: "পাওয়া", pronunciation: "গেট" },
  { id: 48, level: 1, word: "which", meaning: "কোনোটি", pronunciation: "হুইচ" },
  { id: 49, level: 1, word: "go", meaning: "যাওয়া", pronunciation: "গো" },
  {
    id: 50,
    level: 1,
    word: "me",
    meaning: "আমাকে / আমাকে",
    pronunciation: "মি",
  },
  [
    { id: 51, level: 1, word: "when", meaning: "কখন", pronunciation: "হোয়েন" },
    {
      id: 52,
      level: 1,
      word: "make",
      meaning: "তৈরি করা",
      pronunciation: "মেইক",
    },
    { id: 53, level: 1, word: "can", meaning: "পারা", pronunciation: "ক্যান" },
    {
      id: 54,
      level: 1,
      word: "like",
      meaning: "পছন্দ করা / মতো",
      pronunciation: "লাইক",
    },
    { id: 55, level: 1, word: "time", meaning: "সময়", pronunciation: "টাইম" },
    { id: 56, level: 1, word: "no", meaning: "না", pronunciation: "নো" },
    {
      id: 57,
      level: 1,
      word: "just",
      meaning: "শুধু / মাত্র",
      pronunciation: "জাস্ট",
    },
    {
      id: 58,
      level: 1,
      word: "him",
      meaning: "তাকে (পু.)",
      pronunciation: "হিম",
    },
    { id: 59, level: 1, word: "know", meaning: "জানা", pronunciation: "নো" },
    { id: 60, level: 1, word: "take", meaning: "নেওয়া", pronunciation: "টেক" },
    {
      id: 61,
      level: 1,
      word: "people",
      meaning: "মানুষ",
      pronunciation: "পিপল",
    },
    {
      id: 62,
      level: 1,
      word: "into",
      meaning: "ভেতরে",
      pronunciation: "ইন্টু",
    },
    { id: 63, level: 1, word: "year", meaning: "বছর", pronunciation: "ইয়ার" },
    {
      id: 64,
      level: 1,
      word: "your",
      meaning: "তোমার / আপনার",
      pronunciation: "ইওর",
    },
    { id: 65, level: 1, word: "good", meaning: "ভালো", pronunciation: "গুড" },
    { id: 66, level: 1, word: "some", meaning: "কিছু", pronunciation: "সাম" },
    { id: 67, level: 1, word: "could", meaning: "পারতো", pronunciation: "কুড" },
    {
      id: 68,
      level: 1,
      word: "them",
      meaning: "তাদেরকে",
      pronunciation: "দেম",
    },
    { id: 69, level: 1, word: "see", meaning: "দেখা", pronunciation: "সি" },
    { id: 70, level: 1, word: "other", meaning: "অন্য", pronunciation: "আদার" },
    { id: 71, level: 1, word: "than", meaning: "থেকে", pronunciation: "দ্যান" },
    { id: 72, level: 1, word: "then", meaning: "তারপর", pronunciation: "দেন" },
    { id: 73, level: 1, word: "now", meaning: "এখন", pronunciation: "নাউ" },
    { id: 74, level: 1, word: "look", meaning: "দেখা", pronunciation: "লুক" },
    {
      id: 75,
      level: 1,
      word: "only",
      meaning: "শুধুমাত্র",
      pronunciation: "অনলি",
    },
    { id: 76, level: 1, word: "come", meaning: "আসা", pronunciation: "কাম" },
    { id: 77, level: 1, word: "its", meaning: "এর", pronunciation: "ইটস" },
    {
      id: 78,
      level: 1,
      word: "over",
      meaning: "উপর / শেষ",
      pronunciation: "ওভার",
    },
    { id: 79, level: 1, word: "think", meaning: "ভাবা", pronunciation: "থিংক" },
    {
      id: 80,
      level: 1,
      word: "also",
      meaning: "এছাড়াও",
      pronunciation: "অলসো",
    },
    {
      id: 81,
      level: 1,
      word: "back",
      meaning: "পিছনে / ফিরে",
      pronunciation: "ব্যাক",
    },
    { id: 82, level: 1, word: "after", meaning: "পরে", pronunciation: "আফটার" },
    {
      id: 83,
      level: 1,
      word: "use",
      meaning: "ব্যবহার করা",
      pronunciation: "ইউজ",
    },
    { id: 84, level: 1, word: "two", meaning: "দুই", pronunciation: "টু" },
    { id: 85, level: 1, word: "how", meaning: "কীভাবে", pronunciation: "হাউ" },
    {
      id: 86,
      level: 1,
      word: "our",
      meaning: "আমাদের",
      pronunciation: "আওয়ার",
    },
    { id: 87, level: 1, word: "work", meaning: "কাজ", pronunciation: "ওয়ার্ক" },
    {
      id: 88,
      level: 1,
      word: "first",
      meaning: "প্রথম",
      pronunciation: "ফার্স্ট",
    },
    {
      id: 89,
      level: 1,
      word: "well",
      meaning: "ভালভাবে",
      pronunciation: "ওয়েল",
    },
    {
      id: 90,
      level: 1,
      word: "way",
      meaning: "পথ / উপায়",
      pronunciation: "ওয়ে",
    },
    { id: 91, level: 1, word: "even", meaning: "এমনকি", pronunciation: "ইভেন" },
    { id: 92, level: 1, word: "new", meaning: "নতুন", pronunciation: "নিউ" },
    {
      id: 93,
      level: 1,
      word: "want",
      meaning: "চাওয়া",
      pronunciation: "ওয়ান্ট",
    },
    {
      id: 94,
      level: 1,
      word: "because",
      meaning: "কারণ",
      pronunciation: "বিকজ",
    },
    { id: 95, level: 1, word: "any", meaning: "যে কোনো", pronunciation: "এনি" },
    { id: 96, level: 1, word: "these", meaning: "এগুলো", pronunciation: "দিজ" },
    { id: 97, level: 1, word: "give", meaning: "দেওয়া", pronunciation: "গিভ" },
    { id: 98, level: 1, word: "day", meaning: "দিন", pronunciation: "ডে" },
    {
      id: 99,
      level: 1,
      word: "most",
      meaning: "অধিকাংশ",
      pronunciation: "মোস্ট",
    },
    { id: 100, level: 1, word: "us", meaning: "আমাদেরকে", pronunciation: "আস" },
    [
      {
        id: 101,
        level: 2,
        word: "man",
        meaning: "পুরুষ / মানুষ",
        pronunciation: "ম্যান",
      },
      {
        id: 102,
        level: 2,
        word: "find",
        meaning: "খুঁজে পাওয়া",
        pronunciation: "ফাইন্ড",
      },
      {
        id: 103,
        level: 2,
        word: "here",
        meaning: "এখানে",
        pronunciation: "হিয়ার",
      },
      {
        id: 104,
        level: 2,
        word: "thing",
        meaning: "বস্তু",
        pronunciation: "থিং",
      },
      {
        id: 105,
        level: 2,
        word: "give",
        meaning: "দেওয়া",
        pronunciation: "গিভ",
      },
      {
        id: 106,
        level: 2,
        word: "many",
        meaning: "অনেক",
        pronunciation: "মেনি",
      },
      {
        id: 107,
        level: 2,
        word: "well",
        meaning: "ভালভাবে",
        pronunciation: "ওয়েল",
      },
      {
        id: 108,
        level: 2,
        word: "only",
        meaning: "শুধু",
        pronunciation: "অনলি",
      },
      {
        id: 109,
        level: 2,
        word: "those",
        meaning: "ওগুলো",
        pronunciation: "দোজ",
      },
      { id: 110, level: 2, word: "tell", meaning: "বলা", pronunciation: "টেল" },
      {
        id: 111,
        level: 2,
        word: "very",
        meaning: "খুব",
        pronunciation: "ভেরি",
      },
      {
        id: 112,
        level: 2,
        word: "her",
        meaning: "তার (মু.)",
        pronunciation: "হার",
      },
      {
        id: 113,
        level: 2,
        word: "even",
        meaning: "এমনকি",
        pronunciation: "ইভেন",
      },
      {
        id: 114,
        level: 2,
        word: "back",
        meaning: "পিছনে / ফিরে",
        pronunciation: "ব্যাক",
      },
      {
        id: 115,
        level: 2,
        word: "any",
        meaning: "যে কোনো",
        pronunciation: "এনি",
      },
      { id: 116, level: 2, word: "good", meaning: "ভাল", pronunciation: "গুড" },
      {
        id: 117,
        level: 2,
        word: "woman",
        meaning: "মহিলা",
        pronunciation: "উইম্যান",
      },
      {
        id: 118,
        level: 2,
        word: "through",
        meaning: "মাধ্যমে / ভেতর দিয়ে",
        pronunciation: "থ্রু",
      },
      {
        id: 119,
        level: 2,
        word: "life",
        meaning: "জীবন",
        pronunciation: "লাইফ",
      },
      {
        id: 120,
        level: 2,
        word: "child",
        meaning: "শিশু",
        pronunciation: "চাইল্ড",
      },
      {
        id: 121,
        level: 2,
        word: "down",
        meaning: "নিচে",
        pronunciation: "ডাউন",
      },
      {
        id: 122,
        level: 2,
        word: "work",
        meaning: "কাজ",
        pronunciation: "ওয়ার্ক",
      },
      {
        id: 123,
        level: 2,
        word: "may",
        meaning: "হতে পারে",
        pronunciation: "মেই",
      },
      {
        id: 124,
        level: 2,
        word: "after",
        meaning: "পরে",
        pronunciation: "আফটার",
      },
      {
        id: 125,
        level: 2,
        word: "should",
        meaning: "উচিত",
        pronunciation: "শুড",
      },
      {
        id: 126,
        level: 2,
        word: "call",
        meaning: "ডাকা / কল করা",
        pronunciation: "কল",
      },
      {
        id: 127,
        level: 2,
        word: "world",
        meaning: "পৃথিবী",
        pronunciation: "ওয়ার্ল্ড",
      },
      {
        id: 128,
        level: 2,
        word: "over",
        meaning: "উপর / শেষ",
        pronunciation: "ওভার",
      },
      {
        id: 129,
        level: 2,
        word: "school",
        meaning: "বিদ্যালয়",
        pronunciation: "স্কুল",
      },
      {
        id: 130,
        level: 2,
        word: "still",
        meaning: "এখনও",
        pronunciation: "স্টিল",
      },
      {
        id: 131,
        level: 2,
        word: "try",
        meaning: "চেষ্টা করা",
        pronunciation: "ট্রাই",
      },
      {
        id: 132,
        level: 2,
        word: "last",
        meaning: "শেষ",
        pronunciation: "লাস্ট",
      },
      {
        id: 133,
        level: 2,
        word: "ask",
        meaning: "জিজ্ঞাসা করা",
        pronunciation: "আস্ক",
      },
      {
        id: 134,
        level: 2,
        word: "need",
        meaning: "প্রয়োজন",
        pronunciation: "নিড",
      },
      {
        id: 135,
        level: 2,
        word: "too",
        meaning: "অতিরিক্ত / এছাড়াও",
        pronunciation: "টু",
      },
      {
        id: 136,
        level: 2,
        word: "feel",
        meaning: "অনুভব করা",
        pronunciation: "ফিল",
      },
      {
        id: 137,
        level: 2,
        word: "three",
        meaning: "তিন",
        pronunciation: "থ্রি",
      },
      {
        id: 138,
        level: 2,
        word: "state",
        meaning: "অবস্থা / রাজ্য",
        pronunciation: "স্টেট",
      },
      {
        id: 139,
        level: 2,
        word: "never",
        meaning: "কখনো নয়",
        pronunciation: "নেভার",
      },
      {
        id: 140,
        level: 2,
        word: "become",
        meaning: "হওয়া",
        pronunciation: "বিকাম",
      },
      {
        id: 141,
        level: 2,
        word: "between",
        meaning: "মাঝে",
        pronunciation: "বিটুইন",
      },
      {
        id: 142,
        level: 2,
        word: "high",
        meaning: "উচ্চ",
        pronunciation: "হাই",
      },
      {
        id: 143,
        level: 2,
        word: "really",
        meaning: "সত্যিই",
        pronunciation: "রিয়েলি",
      },
      {
        id: 144,
        level: 2,
        word: "something",
        meaning: "কিছু একটা",
        pronunciation: "সামথিং",
      },
      {
        id: 145,
        level: 2,
        word: "most",
        meaning: "অধিকাংশ",
        pronunciation: "মোস্ট",
      },
      {
        id: 146,
        level: 2,
        word: "another",
        meaning: "আরেকটি",
        pronunciation: "অ্যানাদার",
      },
      {
        id: 147,
        level: 2,
        word: "much",
        meaning: "অনেক",
        pronunciation: "মাচ",
      },
      {
        id: 148,
        level: 2,
        word: "family",
        meaning: "পরিবার",
        pronunciation: "ফ্যামিলি",
      },
      {
        id: 149,
        level: 2,
        word: "own",
        meaning: "নিজস্ব",
        pronunciation: "ওন",
      },
      {
        id: 150,
        level: 2,
        word: "leave",
        meaning: "ত্যাগ করা / ছেড়ে যাওয়া",
        pronunciation: "লিভ",
      },
      { id: 151, level: 2, word: "put", meaning: "রাখা", pronunciation: "পুট" },
      {
        id: 152,
        level: 2,
        word: "old",
        meaning: "পুরোনো / বয়স্ক",
        pronunciation: "ওল্ড",
      },
      {
        id: 153,
        level: 2,
        word: "while",
        meaning: "যখন",
        pronunciation: "হোয়াইল",
      },
      {
        id: 154,
        level: 2,
        word: "mean",
        meaning: "অর্থ বোঝানো",
        pronunciation: "মিন",
      },
      {
        id: 155,
        level: 2,
        word: "keep",
        meaning: "রাখা",
        pronunciation: "কিপ",
      },
      {
        id: 156,
        level: 2,
        word: "student",
        meaning: "ছাত্র / শিক্ষার্থী",
        pronunciation: "স্টুডেন্ট",
      },
      {
        id: 157,
        level: 2,
        word: "why",
        meaning: "কেন",
        pronunciation: "হোয়াই",
      },
      {
        id: 158,
        level: 2,
        word: "let",
        meaning: "অনুমতি দেওয়া",
        pronunciation: "লেট",
      },
      {
        id: 159,
        level: 2,
        word: "great",
        meaning: "দারুণ / মহান",
        pronunciation: "গ্রেট",
      },
      { id: 160, level: 2, word: "same", meaning: "একই", pronunciation: "সেম" },
      { id: 161, level: 2, word: "big", meaning: "বড়", pronunciation: "বিগ" },
      {
        id: 162,
        level: 2,
        word: "group",
        meaning: "দল",
        pronunciation: "গ্রুপ",
      },
      {
        id: 163,
        level: 2,
        word: "begin",
        meaning: "শুরু করা",
        pronunciation: "বিগিন",
      },
      {
        id: 164,
        level: 2,
        word: "country",
        meaning: "দেশ",
        pronunciation: "কান্ট্রি",
      },
      {
        id: 165,
        level: 2,
        word: "help",
        meaning: "সহায়তা করা",
        pronunciation: "হেল্প",
      },
      {
        id: 166,
        level: 2,
        word: "talk",
        meaning: "কথা বলা",
        pronunciation: "টক",
      },
      {
        id: 167,
        level: 2,
        word: "where",
        meaning: "কোথায়",
        pronunciation: "হোয়্যার",
      },
      {
        id: 168,
        level: 2,
        word: "turn",
        meaning: "ঘোরা / পালা",
        pronunciation: "টার্ন",
      },
      {
        id: 169,
        level: 2,
        word: "problem",
        meaning: "সমস্যা",
        pronunciation: "প্রবলেম",
      },
      {
        id: 170,
        level: 2,
        word: "every",
        meaning: "প্রতিটি",
        pronunciation: "এভরি",
      },
      {
        id: 171,
        level: 2,
        word: "start",
        meaning: "শুরু",
        pronunciation: "স্টার্ট",
      },
      {
        id: 172,
        level: 2,
        word: "hand",
        meaning: "হাত",
        pronunciation: "হ্যান্ড",
      },
      {
        id: 173,
        level: 2,
        word: "might",
        meaning: "হতে পারে / শক্তি",
        pronunciation: "মাইট",
      },
      {
        id: 174,
        level: 2,
        word: "American",
        meaning: "আমেরিকান",
        pronunciation: "আমেরিকান",
      },
      {
        id: 175,
        level: 2,
        word: "show",
        meaning: "প্রদর্শন করা",
        pronunciation: "শো",
      },
      {
        id: 176,
        level: 2,
        word: "part",
        meaning: "অংশ",
        pronunciation: "পার্ট",
      },
      {
        id: 177,
        level: 2,
        word: "about",
        meaning: "সম্পর্কে",
        pronunciation: "অ্যাবাউট",
      },
      {
        id: 178,
        level: 2,
        word: "against",
        meaning: "বিরুদ্ধে",
        pronunciation: "আগেইনস্ট",
      },
      {
        id: 179,
        level: 2,
        word: "place",
        meaning: "স্থান",
        pronunciation: "প্লেস",
      },
      {
        id: 180,
        level: 2,
        word: "over",
        meaning: "উপর / শেষ",
        pronunciation: "ওভার",
      },
      { id: 181, level: 2, word: "such", meaning: "এমন", pronunciation: "সাচ" },
      {
        id: 182,
        level: 2,
        word: "again",
        meaning: "আবার",
        pronunciation: "আগেইন",
      },
      {
        id: 183,
        level: 2,
        word: "few",
        meaning: "কয়েকটি",
        pronunciation: "ফিউ",
      },
      {
        id: 184,
        level: 2,
        word: "case",
        meaning: "মামলা / কেস",
        pronunciation: "কেস",
      },
      {
        id: 185,
        level: 2,
        word: "most",
        meaning: "অধিকাংশ",
        pronunciation: "মোস্ট",
      },
      {
        id: 186,
        level: 2,
        word: "week",
        meaning: "সপ্তাহ",
        pronunciation: "উইক",
      },
      {
        id: 187,
        level: 2,
        word: "company",
        meaning: "প্রতিষ্ঠান",
        pronunciation: "কম্পানি",
      },
      {
        id: 188,
        level: 2,
        word: "system",
        meaning: "পদ্ধতি / সিস্টেম",
        pronunciation: "সিস্টেম",
      },
      {
        id: 189,
        level: 2,
        word: "each",
        meaning: "প্রতিটি",
        pronunciation: "ইচ",
      },
      {
        id: 190,
        level: 2,
        word: "right",
        meaning: "ঠিক / অধিকার",
        pronunciation: "রাইট",
      },
      {
        id: 191,
        level: 2,
        word: "program",
        meaning: "কার্যক্রম",
        pronunciation: "প্রোগ্রাম",
      },
      {
        id: 192,
        level: 2,
        word: "hear",
        meaning: "শোনা",
        pronunciation: "হিয়ার",
      },
      {
        id: 193,
        level: 2,
        word: "question",
        meaning: "প্রশ্ন",
        pronunciation: "কোয়েশ্চন",
      },
      {
        id: 194,
        level: 2,
        word: "during",
        meaning: "কালে / সময়ে",
        pronunciation: "ডিউরিং",
      },
      {
        id: 195,
        level: 2,
        word: "play",
        meaning: "খেলা / বাজানো",
        pronunciation: "প্লে",
      },
      {
        id: 196,
        level: 2,
        word: "government",
        meaning: "সরকার",
        pronunciation: "গভর্নমেন্ট",
      },
      {
        id: 197,
        level: 2,
        word: "run",
        meaning: "দৌড়ানো / চালানো",
        pronunciation: "রান",
      },
      {
        id: 198,
        level: 2,
        word: "small",
        meaning: "ছোট",
        pronunciation: "স্মল",
      },
      {
        id: 199,
        level: 2,
        word: "number",
        meaning: "সংখ্যা",
        pronunciation: "নাম্বার",
      },
      {
        id: 200,
        level: 2,
        word: "off",
        meaning: "বন্ধ / দূরে",
        pronunciation: "অফ",
      },
    ],
  ],
];
